baseurl: https://miti99.com
languageCode: vi
theme: hugo-theme-stack
title: miti99
defaultContentLanguage: vi
hasCJKLanguage: false
pagination:
  pagerSize: 5
timeout: 600s
enableRobotsTXT: true
timeZone: Asia/Ho_Chi_Minh
enableGitInfo: true
