mainSections:
  - post
featuredImageField: image
rssFullContent: true
favicon: /favicon.png

footer:
  since: 2020
  customText: "Made by miti99 with ❤️"

dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST

sidebar:
  emoji: 🧑‍💻
  subtitle: A developer want to be magician
  avatar:
    enabled: true
    local: true
    src: img/avatar.jpg

article:
  headingAnchor: false
  math: false
  toc: true
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

opengraph:
  twitter:
    site: tienthieusac
    card: summary_large_image

defaultImage:
  opengraph:
    enabled: false
    local: false
    src: img/logo.png

colorScheme:
  toggle: true
  default: dark

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

comments:
  enabled: true
  provider: giscus
  disqusjs:
    shortname: ""
    apiUrl: ""
    apiKey: ""
    admin: ""
    adminLabel: ""
  utterances:
    repo: ""
    issueTerm: "pathname"
    label: ""
  remark42:
    host: ""
    site: ""
    locale: ""
  vssue:
    platform: ""
    owner: ""
    repo: ""
    clientId: ""
    clientSecret: ""
    autoCreateIssue: false
  waline:
    serverURL: ""
    lang: ""
    visitor: ""
    avatar: ""
    emoji: [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta: [ "name", "email", "url" ]
    placeholder: ""
    locale:
      admin: "Admin"
  twikoo:
    envId: ""
    region: ""
    path: ""
    lang: ""
  cactus:
    defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
    serverName: "cactus.chat"
    siteName: ""
  giscus:
    repo: tiennm99/miti99
    repoID: R_kgDOILzXrw
    category: Announcements
    categoryID: DIC_kwDOILzXr84CeYAw
    mapping: pathname
    lightTheme: light
    darkTheme: dark
    reactionsEnabled: 1
    emitMetadata: 0
  gitalk:
    owner: ""
    admin: ""
    repo: ""
    clientID: ""
    clientSecret: ""
  cusdis:
    host: ""
    id: ""
