baseURL = "/"
title = "miti99"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "MiTi99"
description = "MiTi99's personal website"
keywords = "blog,developer,personal"
info = ["Developer", "Wibu"]
avatarURL = "img/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2019
commit = "https://github.com/tiennm99/miti99.eu.org/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []

[params.utterances]
repo = "tiennm99/miti99.eu.org-utterances"
issueTerm = "pathname"
label = ""
theme = "preferred-color-scheme"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
url = "https://github.com/tiennm99/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
url = "https://gitlab.com/miti99/"

[[params.social]]
name = "Facebook"
icon = "fa fa-2x fa-facebook"
url = "https://facebook.com/miti99"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
url = "index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[languages.en.menu.main]]
name = "Contact"
weight = 3
url = "contact/"

[[languages.en.menu.main]]
name = "CV"
weight = 4
url = "https://cv.miti99.eu.org/miti99.pdf"

[[languages.en.menu.main]]
name = "Misc"
weight = 5
url = "misc/"

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"
