baseURL = "/"
title = "miti99"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

googleAnalytics = 183798571
[params.googleTagManager]
id = "GTM-WR9BX9K"
[params.applicationInsights]
connectionString = "InstrumentationKey=995c7eeb-e39f-4dbf-9d36-222d09fd97d8;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/"

[params]
author = "MiTi99"
info = ["Developer", "Wibu"]
description = "MiTi99's personal website"
keywords = "miti99,blog,developer,personal"
avatarURL = "img/avatar.jpg"
favicon_32 = "img/favicon_32.png"
favicon_16 = "img/favicon_16.png"
touchIcon = "img/touchIcon.png"
dateFormat = "January 2, 2006"
since = 2020
maxSeeAlsoItems = 6
commit = "https://github.com/tiennm99/miti99/tree/"
rtl = false
math = true
katex = true
colorScheme = "auto"
hideColorSchemeToggle = false
customCSS = []
customSCSS = []
customJS = []
enableTwemoji = true

[params.utterances]
repo = "tiennm99/miti99"
issueTerm = "pathname"
label = ""
theme = "preferred-color-scheme"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
url = "https://github.com/tiennm99/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
url = "https://gitlab.com/miti99/"

[[params.social]]
name = "Facebook"
icon = "fa fa-2x fa-facebook"
url = "https://facebook.com/miti99"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
url = "index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "About"
weight = 2
url = "about/"

[[menu.main]]
name = "Contact"
weight = 3
url = "contact/"

[[menu.main]]
name = "CV"
weight = 4
url = "https://tiennm99.github.io"

[[menu.main]]
name = "Misc"
weight = 5
url = "misc/"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"
