module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

baseURL: "https://tiennm99.github.io"
title: miti99
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: [ "posts", ]
googleAnalytics: 183798571

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: vi
languages:
  vi:
    languageName: "Tiếng Việt"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archives
          url: archives
          weight: 1
        - name: Posts
          url: posts
          weight: 2
        - name: Search
          url: search
          weight: 3
        - name: Tags
          url: tags
          weight: 4
        - name: About
          url: about
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "miti99's blog"
  author: miti99

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: true
  images: [ "img/logo.png" ]

  profileMode:
    enabled: true
    title: miti99's blog
    subtitle: Một lập trình viên muốn trở thành phù thuỷ
    imageUrl: "img/avatar.jpg"
    imageTitle: miti99's avatar
    imageWidth: 256
    imageHeight: 256
    buttons:
      - name: Archives
        url: archives
      - name: Web CV
        url: https://tiennm99.github.io
      - name: PDF CV
        url: https://cv.miti99.eu.org/miti99.pdf

  homeInfoParams:
    Title: "miti99's blog"
    Content: >
      👋 Chào mừng đến với blog của miti99. Web được tạo ra bởi miti99, sử dụng Hugo và theme PaperMod!

  socialIcons:
    - name: github
      title: View on Github
      url: "https://github.com/tiennm99"
    - name: gitlab
      title: View on Gitlab
      url: "https://gitlab.com/miti99"
    - name: facebook
      title: View on Facebook
      url: "https://facebook.com/miti99"
    - name: youtube
      title: View on Youtube
      url: "https://youtube.com/@miti99"
    - name: linkedin
      title: View on Linkedin
      url: "https://www.linkedin.com/in/miti99"
    - name: x
      title: View on X
      url: "https://twitter.com/tienthieusac"

  editPost:
    URL: "https://github.com/tiennm99/miti99/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "G-JR36Q9NSNP"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
