baseURL:
title: miti99
theme: hugo-coder
languageCode: vi
defaultContentLanguage: vi
paginate: 20
enableEmoji: true

services:
  googleAnalytics:
    id: G-JR36Q9NSNP

markup:
  highlight:
    noClasses: false
    style: monokai

params:
  author: miti99
  license: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>
  description: miti99's personal website
  keywords: blog,developer,personal
  info:
    - Senior Software Engineer
    - Java Game Server Developer
    - Magician
  avatarURL: images/avatar.jpg
  # gravatar: minhtienit99@gmail.com
  favicon_32: images/favicon.png
  dateFormat: January 2, 2006
  since: 2020
  commit: https://github.com/tiennm99/tiennm99.github.io/tree/
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []
  customRemoteJS: []
  enableTwemoji: true
  social:
    - name: github
      icon: fa-brands fa-github fa-2x
      weight: 1
      url: "https://github.com/tiennm99"
    - name: gitlab
      icon: fa-brands fa-gitlab fa-2x
      weight: 2
      url: "https://gitlab.com/miti99"
    - name: facebook
      icon: fa-brands fa-facebook fa-2x
      weight: 3
      url: "https://facebook.com/miti99"
    - name: youtube
      icon: fa-brands fa-youtube fa-2x
      weight: 4
      url: "https://youtube.com/@miti99"
    - name: linkedin
      icon: fa-brands fa-linkedin fa-2x
      weight: 5
      url: "https://www.linkedin.com/in/miti99"
    - name: X
      icon: fa-brands fa-x-twitter fa-2x
      weight: 6
      url: "https://twitter.com/tienthieusac"
    - name: RSS
      icon: fa-solid fa-rss fa-2x
      weight: 7
      url: index.xml
      rel: alternate
      type: application/rss+xml
  giscus:
    repo: tiennm99/tiennm99.github.io
    repoID: R_kgDOILzXrw
    category: Announcements
    categoryID: DIC_kwDOILzXr84CeYAw
    mapping: pathname
    term:
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: top
    theme: dark
    lang:
    loading: lazy

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

languages:
  vi:
    languageName: ":vi:"
    menu:
      main:
        - name: About
          weight: 1
          url: about/
        - name: Blog
          weight: 2
          url: posts/
        - name: Pages
          weight: 3
          url: pages/
        - name: Tags
          weight: 4
          url: tags/
        - name: Web CV
          url: https://tiennm99.github.io/webcv
        - name: PDF CV
          url: https://tiennm99.github.io/cv/miti99.pdf
